version: "3.3"
# Указываем раздел со связанными сервисами

services:
  yw-frontend:
    build: ./
    expose:
      - '3000'
    restart: always
    env_file:
      - .env
    environment:
      - VK_OAUTH_APP_ID=${VK_OAUTH_APP_ID}
      - VK_API_APP_ID=${VK_API_APP_ID}
      - VK_API_SERVICE_KEY=${VK_API_SERVICE_KEY}
      - BASE_URL=${BASE_URL}
      - URWAY_API_URL=${URWAY_API_URL}
    networks:
      - back_front_nginx

networks:
  back_front_nginx:
    external: true